USE HubDados
;
Declare @DATAHOJE date = GETDATE()
 ;
 
WITH CRIAR_NUMEROMOV AS (
SELECT NUMEROMOV,STATUS,DATACRIACAO, DATAEMISSAO,DATASAIDA,DATAMOVIMENTO,DATACANCELAMENTOMOV,DATAEXTRA1,DATAEXTRA2, DATAPROCESSAMENTO FROM CorporeRM.TMOV
WHERE CODTMV IN('1.1.31')
AND YEAR(DATACRIACAO) = '2024'
)
,CRIAR_NUMEROMOV_37 AS (
SELECT NUMEROMOV,STATUS,DATACRIACAO, DATAEMISSAO,DATASAIDA,DATAMOVIMENTO,DATACANCELAMENTOMOV,DATAEXTRA1,DATAEXTRA2, DATAPROCESSAMENTO FROM CorporeRM.TMOV
WHERE CODTMV IN('1.1.37')
AND YEAR(DATACRIACAO) = '2024'
)
,CRIAR_NUMEROMOV_39 AS (
SELECT NUMEROMOV,STATUS,DATACRIACAO, DATAEMISSAO,DATASAIDA,DATAMOVIMENTO,DATACANCELAMENTOMOV,DATAEXTRA1,DATAEXTRA2, DATAPROCESSAMENTO FROM CorporeRM.TMOV
WHERE CODTMV IN('1.1.39')
AND YEAR(DATACRIACAO) = '2024'
)
 
INSERT INTO [FINANCA].dbo._fViagens
 
SELECT A.NUMEROMOV
,A.STATUS AS 'STATUS.31'
,B.STATUS AS 'STATUS.37'
,C.STATUS AS 'STATUS.39'
,CASE WHEN A.STATUS = 'F' AND B.STATUS = 'F' AND C.STATUS = 'F' THEN 'FINALIZADO .39 - PRESTOU CONTAS E ENCAMINHOU PARA ANALISE UFC - FINALIZADO'
WHEN A.STATUS = 'F' AND B.STATUS = 'A' AND C.STATUS IS NULL  THEN 'RECEBEU ADIANTAMENTO E NÃO PRESTOU CONTAS'
WHEN A.STATUS = 'F' AND B.STATUS = 'F' AND C.STATUS = 'A'  THEN 'RECEBEU ADIANTAMENTO, PRESTOU CONTAS E NÃO REALIZOU A VIAGEM'
WHEN A.STATUS = 'F' AND B.STATUS IS NULL AND C.STATUS = 'R'  THEN 'CASOS EXCEPCIONAIS UII'
WHEN A.STATUS = 'C' AND B.STATUS = 'C' AND C.STATUS IS NULL THEN 'CANCELADO - ADIANTAMENTO ANTES DE PAGAR'
WHEN A.STATUS = 'C' AND B.STATUS IS NULL AND C.STATUS IS NULL THEN 'CANCELADO'
WHEN A.STATUS = 'F' AND B.STATUS IS NULL AND C.STATUS = 'F' THEN 'NÃO RECEBEU ADIANTAMENTO E PRESTOU CONTAS - FINALIZADO'
WHEN A.STATUS = 'F' AND B.STATUS IS NULL AND C.STATUS = 'A' THEN 'NÃO RECEBEU ADIANTAMENTO E PRESTOU CONTAS - NÃO FOI FINALIZADO'
WHEN A.STATUS = 'R' AND B.STATUS IS NULL AND C.STATUS = 'R' THEN 'NÃO AUTORIZADO PELO SUPERIOR - PENDENTE AUTORIZAÇÃO'
WHEN A.STATUS = 'R' AND B.STATUS IS NULL AND C.STATUS IS NULL THEN 'NÃO AUTORIZADO PELO SUPERIOR - POSSIVEL PASSAGEM AEREA'
WHEN A.STATUS = 'A' AND B.STATUS IS NULL AND C.STATUS IS NULL THEN 'ZERADAS PENDENTES DE FATURAMENTO'
 
ELSE A.STATUS END AS 'DESCSTATUS'
,@DATAHOJE as 'DATAATUALIZACAO'
,A.DATACRIACAO, A.DATAEMISSAO, A.DATASAIDA, A.DATAMOVIMENTO, A.DATACANCELAMENTOMOV, A.DATAEXTRA1, A.DATAEXTRA2, A.DATAPROCESSAMENTO
,B.DATACRIACAO, B.DATAEMISSAO, B.DATASAIDA, B.DATAMOVIMENTO, B.DATACANCELAMENTOMOV, B.DATAEXTRA1, B.DATAEXTRA2, B.DATAPROCESSAMENTO
,C.DATACRIACAO, C.DATAEMISSAO, C.DATASAIDA, C.DATAMOVIMENTO, C.DATACANCELAMENTOMOV, C.DATAEXTRA1, C.DATAEXTRA2, C.DATAPROCESSAMENTO
FROM CRIAR_NUMEROMOV A
LEFT JOIN CRIAR_NUMEROMOV_37 B
ON A.NUMEROMOV = B.NUMEROMOV
LEFT JOIN CRIAR_NUMEROMOV_39 C
ON A.NUMEROMOV = C.NUMEROMOV
 
 
ORDER BY B.NUMEROMOV DESC