USE HUBDADOS
;

SELECT A.CODIGO, A.DESCRICAO,
SUBSTRING(A.CODIGO, 1,1) AS NVL1, B.DESCRICAO AS DESCRICAONVL1
, SUBSTRING(A.CODIGO, 1,4) AS NVL2, C.DESCRICAO AS DESCRICAONVL2
, SUBSTRING(A.CODIGO, 1,6) AS NVL3, D.DESCRICAO AS DESCRICAONVL3
, SUBSTRING(A.CODIGO, 1,8) AS NVL4, E.DESCRICAO AS DESCRICAONVL4
, SUBSTRING(A.CODIGO, 1,12) AS NVL5, F.DESCRICAO AS DESCRICAONVL5
, SUBSTRING(A.CODIGO, 1,15) AS NVL6, G.DESCRICAO AS DESCRICAONVL6
, SUBSTRING(A.CODIGO, 1,18) AS NVL7, H.DESCRICAO AS DESCRICAONVL7
, SUBSTRING(A.CODIGO, 1,21) AS NVL8, I.DESCRICAO AS DESCRICAONVL8
, SUBSTRING(A.CODIGO, 1,24) AS NVL9, J.DESCRICAO AS DESCRICAONVL9
, SUBSTRING(A.CODIGO, 1,28) AS NVL10, K.DESCRICAO AS DESCRICAONVL10
, SUBSTRING(A.CODIGO, 1,31) AS NVL11, L.DESCRICAO AS DESCRICAONVL11
, SUBSTRING(A.CODIGO, 1,34) AS NVL12, M.DESCRICAO AS DESCRICAONVL12
INTO #TBVSECAO
FROM CorporeRM.PSECAO A
LEFT JOIN CorporeRM.PSECAO B
ON SUBSTRING(A.CODIGO, 1,1) = B.CODIGO
LEFT JOIN CorporeRM. PSECAO C
ON SUBSTRING(A.CODIGO, 1,4) = C.CODIGO
LEFT JOIN CorporeRM.PSECAO D
ON SUBSTRING(A.CODIGO, 1,6) = D.CODIGO
LEFT JOIN CorporeRM.PSECAO E
ON SUBSTRING(A.CODIGO, 1,8) = E.CODIGO
LEFT JOIN CorporeRM.PSECAO F
ON SUBSTRING(A.CODIGO, 1,12) = F.CODIGO
LEFT JOIN CorporeRM.PSECAO G
ON SUBSTRING(A.CODIGO, 1,15) = G.CODIGO
LEFT JOIN CorporeRM.PSECAO H
ON SUBSTRING(A.CODIGO, 1,18) = H.CODIGO
LEFT JOIN CorporeRM.PSECAO I
ON SUBSTRING(A.CODIGO, 1,21) = I.CODIGO
LEFT JOIN CorporeRM.PSECAO J
ON SUBSTRING(A.CODIGO, 1,24) = J.CODIGO
LEFT JOIN CorporeRM.PSECAO K
ON SUBSTRING(A.CODIGO, 1,28) = K.CODIGO
LEFT JOIN CorporeRM.PSECAO L
ON SUBSTRING(A.CODIGO, 1,31) = L.CODIGO
LEFT JOIN CorporeRM.PSECAO M
ON SUBSTRING(A.CODIGO, 1,34) = M.CODIGO

WHERE LEN(A.CODIGO) = 34 AND A.CODIGO LIKE '1%'

SELECT * FROM #TBVSECAO

DROP TABLE #TBVSECAO