USE HubDados
;

WITH SELECAO_NUMEROMOV AS (SELECT DISTINCT NUMEROMOV FROM CorporeRM.TMOV 
WHERE YEAR(DATACRIACAO) = '2024' AND CODTMV LIKE '1.1.31')

SELECT * FROM CorporeRM.TMOV A

INNER JOIN SELECAO_NUMEROMOV B
ON A.NUMEROMOV = B.NUMEROMOV
WHERE A.NUMEROMOV LIKE '113172' AND A.CODTMV IN ('1.1.31', '1.1.39', '1.1.37')
ORDER BY DATACRIACAO DESC