USE FINANCA; --_TCNT

DECLARE @DATAHOJE DATETIME = GETDATE()
;

DROP TABLE _TCNT

SELECT  
A.IDCNT,
CODIGOCONTRATO,
CODCFO,
DATACONTRATO,
DATAINICIO,
DATAFIM,
CODSTACNT,
VALORCONTRATO,
CODVEN,
NOME,
CODDEPARTAMENTO,
DT_CONTRATO,
@DATAHOJE AS 'DATAATUALIZACAO'
INTO dbo._TCNT 
FROM HubDados.CorporeRM.TCNT A
INNER JOIN HUBDADOS.CorporeRM.TCNTCOMPL B
ON A.IDCNT = B.IDCNT
WHERE YEAR(DATACONTRATO) IN ('2024', '2025')

SELECT * FROM _TCNT