USE FINANCA; --_TMOV

DECLARE @DATAHOJE DATETIME = GETDATE()
;

DROP TABLE _TMOV


SELECT  
IDMOV,
CODLOCENTREGA,
CODUSUARIO,
CODCFO,
NUMEROMOV,
STATUS,
DATAEMISSAO,
VALORBRUTO,
CODVEN1,
HISTORICO,
CAMPOLIVRE1,
@DATAHOJE AS 'DATAATUALIZACAO'
INTO dbo._TMOV FROM HubDados.CorporeRM.TMOV
WHERE CODTMV = '2.2.14' AND YEAR(DATAEMISSAO) = '2025' AND STATUS <> 'C'

SELECT * FROM _TMOV