USE HUBDADOS;

SELECT A.IDCNT, A.CODIGOCONTRATO, B.IDPRD, B.PRECOFATURAMENTO, A.VALORCONTRATO FROM CorporeRM.TCNT A
INNER JOIN CorporeRM.TITMCNT B
ON A.IDCNT = B.IDCNT
LEFT JOIN CorporeRM.TITMCNTADITIVO C
ON A.IDCNT = C.IDCNT
WHERE A.CODIGOCONTRATO LIKE '%MAR0.000017.25%'

SELECT * FROM CorporeRM.TITMMOV
WHERE IDMOV = '5152625'