USE HUBDADOS;

SELECT  A.IDCNT, A.CODIGOCONTRATO, B.IDPRD, FORMAT(B.PRECOFATURAMENTO, 'C', 'PT-BR') AS 'PREÇO FATURAMENTO', FORMAT(A.VALORCONTRATO, 'C', 'PT-BR') AS 'VALOR CONTRATO' FROM CorporeRM.TCNT A
INNER JOIN CorporeRM.TITMCNT B
ON A.IDCNT = B.IDCNT
LEFT JOIN CorporeRM.TITMCNTADITIVO C
ON A.IDCNT = C.IDCNT
WHERE A.CODIGOCONTRATO LIKE '%SJR0.000322.25%'
ORDER BY IDPRD ASC

SELECT B.IDMOV, B.NUMEROMOV, C.NOME, C.NOMEFANTASIA, A.IDPRD, D.NOMEFANTASIA AS 'PRODUTO', FORMAT(A.PRECOUNITARIO, 'C', 'PT-BR') AS 'VALOR', FORMAT(A.QUANTIDADE, '#,0', 'PT-BR') AS 'QUANTIDADE', FORMAT(SUM(A.PRECOUNITARIO * A.QUANTIDADE), 'C', 'PT-BR') AS 'VALOR TOTAL', B.DATAEMISSAO FROM CorporeRM.TITMMOV A
INNER JOIN CorporeRM.TMOV B
ON A.IDMOV = B.IDMOV
INNER JOIN CORPORERM.FCFO C
ON B.CODCFO = C.CODCFO
INNER JOIN CorporeRM.TPRD D
ON A.IDPRD = D.IDPRD
WHERE B.IDMOV = '5227825'
GROUP BY GROUPING SETS((B.IDMOV, A.IDPRD, D.NOMEFANTASIA, A.PRECOUNITARIO, A.QUANTIDADE, B.DATAEMISSAO), (B.IDMOV)), B.NUMEROMOV, C.NOME, C.NOMEFANTASIA
ORDER BY CASE WHEN A.IDPRD IS NULL THEN 1 ELSE 0 END, A.IDPRD ASC

/*SELECT IDCNT, FORMAT(VALOR, 'C', 'PT-BR') AS 'VALOR' FROM CorporeRM.TITMCNTADITIVO
WHERE IDCNT = '90064123'*/ 	