SELECT TOP 1 * FROM [HubDados].[CorporeRM].[CuboReal]
SELECT TOP 1 * FROM [HubDados].[CorporeRM].[DadosAcademicos]
SELECT TOP 1 * FROM [HubDados].[CorporeRM].[LogEmailBatidaManual]
SELECT TOP 1 * FROM [HubDados].[CorporeRM].[pfcompl]
SELECT TOP 1 * FROM [HubDados].[CorporeRM].[Sinco_Contas]
SELECT TOP 1 * FROM [HubDados].[IntegradorDeVendas].[Venda]
SELECT TOP 1 * FROM [HubDados].[RAE].[Contato]
SELECT TOP 1 * FROM [HubDados].[Receita].[CartaoCNPJ_SP]