USE HubDados;


DECLARE @CC_FEIRA_DIARIAS AS TABLE (IDMOV VARCHAR(20))
INSERT INTO @CC_FEIRA_DIARIAS
SELECT DISTINCT IDMOV FROM CorporeRM.TITMMOVRATCCU WHERE CODCCUSTO LIKE '00059.000005.019'
;
WITH TVEN AS (SELECT CODVEN,NOME,CODPESSOA,CARGO FROM CorporeRM.TVEN)
, DEPTO AS (SELECT DISTINCT CODDEPARTAMENTO,NOME FROM CorporeRM.GDEPTO WHERE CODFILIAL = 1)
, FORNECEDOR AS (SELECT CODCFO,NOME,NOMEFANTASIA FROM CorporeRM.FCFO)

SELECT
A.IDMOV
,A.CODDEPARTAMENTO
,G.NOME
,CODUSUARIO
,UPPER(F.NOMEFANTASIA) AS FUNCIONARIO
,NUMEROMOV
,CODTMV
,STATUS
,DATACRIACAO
,DATAEMISSAO
,VALORLIQUIDOORIG
,B.NOME AS NOME1
,C.NOME AS NOME2
,D.NOME AS NOME3
,E.NOME AS NOME4
,Historico
,DATAEXTRA1
,DATAEXTRA2
FROM CorporeRM.TMOV A
LEFT JOIN TVEN B
ON A.CODVEN1 = B.CODVEN
LEFT JOIN TVEN C
ON A.CODVEN2 = C.CODVEN
LEFT JOIN TVEN D
ON A.CODVEN3 = D.CODVEN
LEFT JOIN TVEN E
ON A.CODVEN4 = E.CODVEN
LEFT JOIN FORNECEDOR F
ON A.CODCFO = F.CODCFO
LEFT JOIN DEPTO G
ON A.CODDEPARTAMENTO COLLATE SQL_Latin1_General_CP1_CI_AI = G.CODDEPARTAMENTO
WHERE IDMOV IN (SELECT * fROM @CC_FEIRA_DIARIAS) AND STATUS <> 'C' 
ORDER BY DATACRIACAO DESC