USE FINANCA
;
WITH EXEC_ERS AS (
SELECT A.*, B.CLASSIFICA FROM FatoFechamento A
INNER JOIN _CCERs B
ON A.CODGERENCIAL = B.CODGERENCIAL
WHERE YEAR([DATA]) = '2024' AND A.TIPO = 'DESPESA'
)
,
FILTROS_FORA AS (SELECT DISTINCT * FROM FatoFechamento
WHERE (YEAR([DATA]) = '2024'
AND TIPO = 'DESPESA' 
AND (LEFT (PROJETO, 31) = 'SP - Atendimento Presencial ER' 
OR LEFT (PROJETO, 31) = 'SP Atendimento Presencial - ER' 
OR LEFT (PROJETO, 29) = 'SP Atendimento Presencial ER'
OR LEFT (PROJETO, 30) = 'SP - Atendimento Presencial -'
OR LEFT (PROJETO, 30) = 'SP - Atendimento Presencial ER'
)))
SELECT IDRATEIO, UNIFICAVALOR, CLASSIFICA, CODGERENCIAL, COMPLEMENTO, FORNECEDOR, PROJETO, ACAO, CONTA_FECHAMENTO, [DATA], DESCNVL6, COD_CONTA, TIPO
FROM EXEC_ERS
WHERE PROJETO NOT IN (SELECT PROJETO FROM FILTROS_FORA)