queries = { 
"provisao_query": """

WITH _NOVENTAENOVE AS (
SELECT IDMOV,DATAMOVIMENTO,STATUS, B.IDMOVDESTINO as 'IDMOV_1198'
FROM CorporeRM.TMOV A
LEFT JOIN CORPORERM.TMOVRELAC B
ON A.IDMOV = B.IDMOVORIGEM 
WHERE CODTMV = '1.1.99' AND YEAR(DATAMOVIMENTO) BETWEEN 2020 AND 2024)

, FINAL AS(
SELECT A.*,B.IDMOVDESTINO as 'IDMOV_1223' FROM _NOVENTAENOVE A
LEFT JOIN CORPORERM.TMOVRELAC B
ON A.IDMOV_1198 = B.IDMOVORIGEM)
 
,TVEN AS (SELECT * FROM CorporeRM.TVEN)

,GDEPTO AS (SELECT * FROM CorporeRM.GDEPTO WHERE CODFILIAL = 1)

, TOTAL AS (
SELECT B.CODFILIAL
,B.IDMOV AS 'IDENTIFICADOR'
,B.CODTMV AS 'Tipo do Movtº'
,B.DATAEMISSAO
,B.NUMEROMOV AS 'Nº do Movimento'
,B.VALORBRUTOORIG AS 'Valor do Documento'
,B.CODCFO AS 'Fornecedor'
,C.NOMEFANTASIA AS 'Razão Social'
,C.CGCCFO AS 'CPF/CNPJ'
,C.CODETD AS 'UF Cli/For'
,B.CAMPOLIVRE1 AS 'N°ContratoRM:'
,E.PROCESSO
,F.NOME AS 'Escritorios Regionais'
,G.NOME AS 'Usuário'
,B.DATACANCELAMENTOMOV
,CASE WHEN B.DATACANCELAMENTOMOV IS NULL OR B.DATACANCELAMENTOMOV = '' THEN 0 ELSE -B.VALORBRUTOORIG END AS 'Valor Estornado / Cancelado'
,CASE WHEN B.DATACANCELAMENTOMOV IS NULL OR B.DATACANCELAMENTOMOV = '' THEN NULL ELSE FORMAT(B.DATACANCELAMENTOMOV, 'MMMM/yyyy','PT-BR') END AS 'Mês Cancelamento'
,CASE WHEN B.DATAEMISSAO <= B.DATACANCELAMENTOMOV THEN NULL ELSE B.VALORBRUTOORIG END AS 'Valor Provisionado'
,FORMAT(B.DATAEMISSAO, 'yyyy','PT-BR') AS 'Ano Provisão'
,FORMAT(B.DATAEMISSAO, 'MMMM/yyyy','PT-BR') AS 'Mês Provisão'
,H.NUMEROMOV as 'NF'
,CASE WHEN B.DATAEMISSAO <= B.DATACANCELAMENTOMOV THEN NULL WHEN H.NUMEROMOV IS NULL THEN B.VALORBRUTOORIG ELSE NULL END AS 'Movimentos Pendentes de Pagamento Pagar'
,D.NOME AS CONTRATO
,CASE WHEN D.CODSTACNT = '00001' THEN 'ABERTO' WHEN D.CODSTACNT = '00002' THEN 'ENCERRADO' WHEN D.CODSTACNT = '00008' THEN 'ENCERRADO POR VIGENCIA' ELSE 'ABERTO' END AS 'situação do contrato'
,I.NOME  AS GESTOR
,J.NOME AS GERENTE
,K.NOME AS 'UNIDADE'
FROM FINAL A
LEFT JOIN CorporeRM.TMOV B
ON A.IDMOV = B.IDMOV
LEFT JOIN CorporeRM.FCFO C
ON B.CODCFO = C.CODCFO
LEFT JOIN CorporeRM.TCNT D
ON B.CAMPOLIVRE1 COLLATE Latin1_General_CI_AI = D.CODIGOCONTRATO
LEFT JOIN CorporeRM.TCNTCOMPL E
ON D.IDCNT = E.IDCNT
LEFT JOIN GDEPTO F
ON B.CODDEPARTAMENTO COLLATE Latin1_General_CI_AI = F.CODDEPARTAMENTO
LEFT JOIN CorporeRM.TVEN G
ON (B.CODVEN1 = G.CODVEN OR (B.CODVEN1 IS NULL AND B.CODVEN2 = G.CODVEN))
LEFT JOIN CorporeRM.TMOV H
ON A.IDMOV_1223 = H.IDMOV
LEFT JOIN TVEN I
ON D.CODVEN COLLATE SQL_Latin1_General_CP1_CI_AI = I.CODVEN
LEFT JOIN TVEN J
ON D.CODVEN2 COLLATE SQL_Latin1_General_CP1_CI_AI = J.CODVEN
LEFT JOIN GDEPTO K
ON D.CODDEPARTAMENTO COLLATE Latin1_General_CI_AS = K.CODDEPARTAMENTO
)

, PROVISAO AS (
	SELECT [Ano Provisão] AS 'ANO',
	MONTH(DATAEMISSAO) AS 'MES',
	SUM([Valor do Documento]) AS 'VALOR DOCUMENTO',
	COUNT(IDENTIFICADOR) AS 'QUANTIDADE DE MOVIMENTO'
	FROM TOTAL
	GROUP BY [Ano Provisão], MONTH(DATAEMISSAO)
)

SELECT * FROM PROVISAO
ORDER BY ANO, MES ASC""",
"fornecedor_query": """

WITH _NOVENTAENOVE AS (
SELECT IDMOV,DATAMOVIMENTO,STATUS, B.IDMOVDESTINO as 'IDMOV_1198'
FROM CorporeRM.TMOV A
LEFT JOIN CORPORERM.TMOVRELAC B
ON A.IDMOV = B.IDMOVORIGEM 
WHERE CODTMV = '1.1.99' AND YEAR(DATAMOVIMENTO) BETWEEN 2020 AND 2024)

, FINAL AS(
SELECT A.*,B.IDMOVDESTINO as 'IDMOV_1223' FROM _NOVENTAENOVE A
LEFT JOIN CORPORERM.TMOVRELAC B
ON A.IDMOV_1198 = B.IDMOVORIGEM)
 
,TVEN AS (SELECT * FROM CorporeRM.TVEN)

,GDEPTO AS (SELECT * FROM CorporeRM.GDEPTO WHERE CODFILIAL = 1)

, TOTAL AS (
SELECT B.CODFILIAL
,B.IDMOV AS 'IDENTIFICADOR'
,B.CODTMV AS 'Tipo do Movtº'
,B.DATAEMISSAO
,B.NUMEROMOV AS 'Nº do Movimento'
,B.VALORBRUTOORIG AS 'Valor do Documento'
,B.CODCFO AS 'Fornecedor'
,C.NOMEFANTASIA AS 'Razão Social'
,C.CGCCFO AS 'CPF/CNPJ'
,C.CODETD AS 'UF Cli/For'
,B.CAMPOLIVRE1 AS 'N°ContratoRM:'
,E.PROCESSO
,F.NOME AS 'Escritorios Regionais'
,G.NOME AS 'Usuário'
,B.DATACANCELAMENTOMOV
,CASE WHEN B.DATACANCELAMENTOMOV IS NULL OR B.DATACANCELAMENTOMOV = '' THEN 0 ELSE -B.VALORBRUTOORIG END AS 'Valor Estornado / Cancelado'
,CASE WHEN B.DATACANCELAMENTOMOV IS NULL OR B.DATACANCELAMENTOMOV = '' THEN NULL ELSE FORMAT(B.DATACANCELAMENTOMOV, 'MMMM/yyyy','PT-BR') END AS 'Mês Cancelamento'
,CASE WHEN B.DATAEMISSAO <= B.DATACANCELAMENTOMOV THEN NULL ELSE B.VALORBRUTOORIG END AS 'Valor Provisionado'
,FORMAT(B.DATAEMISSAO, 'yyyy','PT-BR') AS 'Ano Provisão'
,FORMAT(B.DATAEMISSAO, 'MMMM/yyyy','PT-BR') AS 'Mês Provisão'
,CASE WHEN H.NUMEROMOV IS NULL OR H.NUMEROMOV = '' THEN 0 ELSE B.VALORBRUTOORIG END AS 'VALOR PAGO'
,H.NUMEROMOV as 'NF'
,CASE WHEN B.DATAEMISSAO <= B.DATACANCELAMENTOMOV THEN NULL WHEN H.NUMEROMOV IS NULL THEN B.VALORBRUTOORIG ELSE NULL END AS 'Movimentos Pendentes de Pagamento Pagar'
,D.NOME AS CONTRATO
,CASE WHEN D.CODSTACNT = '00001' THEN 'ABERTO' WHEN D.CODSTACNT = '00002' THEN 'ENCERRADO' WHEN D.CODSTACNT = '00008' THEN 'ENCERRADO POR VIGENCIA' ELSE 'ABERTO' END AS 'situação do contrato'
,I.NOME  AS GESTOR
,J.NOME AS GERENTE
,K.NOME AS 'UNIDADE'
FROM FINAL A
LEFT JOIN CorporeRM.TMOV B
ON A.IDMOV = B.IDMOV
LEFT JOIN CorporeRM.FCFO C
ON B.CODCFO = C.CODCFO
LEFT JOIN CorporeRM.TCNT D
ON B.CAMPOLIVRE1 COLLATE Latin1_General_CI_AI = D.CODIGOCONTRATO
LEFT JOIN CorporeRM.TCNTCOMPL E
ON D.IDCNT = E.IDCNT
LEFT JOIN GDEPTO F
ON B.CODDEPARTAMENTO COLLATE Latin1_General_CI_AI = F.CODDEPARTAMENTO
LEFT JOIN CorporeRM.TVEN G
ON (B.CODVEN1 = G.CODVEN OR (B.CODVEN1 IS NULL AND B.CODVEN2 = G.CODVEN))
LEFT JOIN CorporeRM.TMOV H
ON A.IDMOV_1223 = H.IDMOV
LEFT JOIN TVEN I
ON D.CODVEN COLLATE SQL_Latin1_General_CP1_CI_AI = I.CODVEN
LEFT JOIN TVEN J
ON D.CODVEN2 COLLATE SQL_Latin1_General_CP1_CI_AI = J.CODVEN
LEFT JOIN GDEPTO K
ON D.CODDEPARTAMENTO COLLATE Latin1_General_CI_AS = K.CODDEPARTAMENTO
)

, FORNECEDOR AS (
	SELECT
	[Razão Social] AS 'RAZÃO SOCIAL',
	SUM([Valor Provisionado]) AS 'VALOR_PROVISIONADO',
	SUM([VALOR PAGO]) AS 'VALOR_PAGO',
	SUM([Movimentos Pendentes de Pagamento Pagar]) AS 'MOVIMENTOS_PENDENTES_DE_PAGAMENTO_PAGAR'
	FROM TOTAL
	GROUP BY [Razão Social]

)

SELECT 
	[RAZÃO SOCIAL],
	VALOR_PROVISIONADO AS 'VALOR PROVISIONADO',
	VALOR_PAGO AS 'VALOR PAGO',
	MOVIMENTOS_PENDENTES_DE_PAGAMENTO_PAGAR AS 'MOVIMENTOS PENDENTES DE PAGAMENTO PAGAR'
	FROM FORNECEDOR
ORDER BY [MOVIMENTOS PENDENTES DE PAGAMENTO PAGAR] DESC""",
"query_pagamento": """WITH _NOVENTAENOVE AS (
SELECT IDMOV,DATAMOVIMENTO,STATUS, B.IDMOVDESTINO as 'IDMOV_1198'
FROM CorporeRM.TMOV A
LEFT JOIN CORPORERM.TMOVRELAC B
ON A.IDMOV = B.IDMOVORIGEM 
WHERE CODTMV = '1.1.99' AND YEAR(DATAMOVIMENTO) BETWEEN 2020 AND 2024)

, FINAL AS(
SELECT A.*,B.IDMOVDESTINO as 'IDMOV_1223' FROM _NOVENTAENOVE A
LEFT JOIN CORPORERM.TMOVRELAC B
ON A.IDMOV_1198 = B.IDMOVORIGEM)
 
,TVEN AS (SELECT * FROM CorporeRM.TVEN)

,GDEPTO AS (SELECT * FROM CorporeRM.GDEPTO WHERE CODFILIAL = 1)

, TOTAL AS (
SELECT B.CODFILIAL
,B.IDMOV AS 'IDENTIFICADOR'
,B.CODTMV AS 'Tipo do Movtº'
,B.DATAEMISSAO
,B.NUMEROMOV AS 'Nº do Movimento'
,B.VALORBRUTOORIG AS 'Valor do Documento'
,B.CODCFO AS 'Fornecedor'
,C.NOMEFANTASIA AS 'Razão Social'
,C.CGCCFO AS 'CPF/CNPJ'
,C.CODETD AS 'UF Cli/For'
,B.CAMPOLIVRE1 AS 'N°ContratoRM:'
,E.PROCESSO
,F.NOME AS 'Escritorios Regionais'
,G.NOME AS 'Usuário'
,B.DATACANCELAMENTOMOV
,CASE WHEN B.DATACANCELAMENTOMOV IS NULL OR B.DATACANCELAMENTOMOV = '' THEN 0 ELSE -B.VALORBRUTOORIG END AS 'Valor Estornado / Cancelado'
,CASE WHEN B.DATACANCELAMENTOMOV IS NULL OR B.DATACANCELAMENTOMOV = '' THEN NULL ELSE FORMAT(B.DATACANCELAMENTOMOV, 'MMMM/yyyy','PT-BR') END AS 'Mês Cancelamento'
,CASE WHEN B.DATAEMISSAO <= B.DATACANCELAMENTOMOV THEN NULL ELSE B.VALORBRUTOORIG END AS 'Valor Provisionado'
,FORMAT(B.DATAEMISSAO, 'yyyy','PT-BR') AS 'Ano Provisão'
,FORMAT(B.DATAEMISSAO, 'MMMM/yyyy','PT-BR') AS 'Mês Provisão'
,CASE WHEN H.NUMEROMOV IS NULL OR H.NUMEROMOV = '' THEN 0 ELSE B.VALORBRUTOORIG END AS 'VALOR PAGO'
,H.NUMEROMOV as 'NF'
,CASE WHEN B.DATAEMISSAO <= B.DATACANCELAMENTOMOV THEN NULL WHEN H.NUMEROMOV IS NULL THEN B.VALORBRUTOORIG ELSE NULL END AS 'Movimentos Pendentes de Pagamento Pagar'
,D.NOME AS CONTRATO
,CASE WHEN D.CODSTACNT = '00001' THEN 'ABERTO' WHEN D.CODSTACNT = '00002' THEN 'ENCERRADO' WHEN D.CODSTACNT = '00008' THEN 'ENCERRADO POR VIGENCIA' ELSE 'ABERTO' END AS 'situação do contrato'
,I.NOME  AS GESTOR
,J.NOME AS GERENTE
,K.NOME AS 'UNIDADE'
FROM FINAL A
LEFT JOIN CorporeRM.TMOV B
ON A.IDMOV = B.IDMOV
LEFT JOIN CorporeRM.FCFO C
ON B.CODCFO = C.CODCFO
LEFT JOIN CorporeRM.TCNT D
ON B.CAMPOLIVRE1 COLLATE Latin1_General_CI_AI = D.CODIGOCONTRATO
LEFT JOIN CorporeRM.TCNTCOMPL E
ON D.IDCNT = E.IDCNT
LEFT JOIN GDEPTO F
ON B.CODDEPARTAMENTO COLLATE Latin1_General_CI_AI = F.CODDEPARTAMENTO
LEFT JOIN CorporeRM.TVEN G
ON (B.CODVEN1 = G.CODVEN OR (B.CODVEN1 IS NULL AND B.CODVEN2 = G.CODVEN))
LEFT JOIN CorporeRM.TMOV H
ON A.IDMOV_1223 = H.IDMOV
LEFT JOIN TVEN I
ON D.CODVEN COLLATE SQL_Latin1_General_CP1_CI_AI = I.CODVEN
LEFT JOIN TVEN J
ON D.CODVEN2 COLLATE SQL_Latin1_General_CP1_CI_AI = J.CODVEN
LEFT JOIN GDEPTO K
ON D.CODDEPARTAMENTO COLLATE Latin1_General_CI_AS = K.CODDEPARTAMENTO
)

, PAGAMENTO AS (
	SELECT
	CASE WHEN [Mês Provisão] LIKE 'JANEIRO%' THEN 1
	WHEN [Mês Provisão] LIKE 'FEVEREIRO%' THEN 2
	WHEN [Mês Provisão] LIKE 'MARÇO%' THEN 3
	WHEN [Mês Provisão] LIKE 'ABRIL%' THEN 4
	WHEN [Mês Provisão] LIKE 'MAIO%' THEN 5
	WHEN [Mês Provisão] LIKE 'JUNHO%' THEN 6
	WHEN [Mês Provisão] LIKE 'JULHO%' THEN 7
	WHEN [Mês Provisão] LIKE 'AGOSTO%' THEN 8
	WHEN [Mês Provisão] LIKE 'SETEMBRO%' THEN 9
	WHEN [Mês Provisão] LIKE 'OUTUBRO%' THEN 10
	WHEN [Mês Provisão] LIKE 'NOVEMBRO%' THEN 11
	WHEN [Mês Provisão] LIKE 'DEZEMBRO%' THEN 12 ELSE NULL END AS 'MES',
	SUM([VALOR PAGO]) AS 'VALOR PAGO',
	COUNT(IDENTIFICADOR) AS 'QUANTIDADE DE MOVIMENTO'
	FROM TOTAL
	WHERE [Ano Provisão] IN ('2023', '2024')
	GROUP BY [Mês Provisão]
)

SELECT * FROM PAGAMENTO
ORDER BY MES ASC"""
}