queries = {
"pgto_query": """
    DECLARE @DATAINICIO DATE = '01/01/24';
    DECLARE @DATAFIM DATE = GETDATE();
   
    WITH TMOV AS (
        SELECT IDMOV, DATAEMISSAO, CODTMV, CODCFO
        FROM CorporeRM.TMOV WITH (NOLOCK)
        WHERE [DATAEMISSAO] BETWEEN @DATAINICIO AND @DATAFIM
        AND CODTMV IN ('2.1.07','2.1.13','2.1.14','2.2.14')
    ),
   
    ITMMOV AS (
        SELECT IDMOV, IDPRD
        FROM CorporeRM.TITMMOV WITH (NOLOCK)
    ),
   
    DESCR_MOV AS (
        SELECT CODTMV, DESCMOV
        FROM [FINANCA].[dbo].[descricao_CODTMV] WITH (NOLOCK)
    ),
   
    TPRD AS (
        SELECT IDPRD, NOMEFANTASIA
        FROM CorporeRM.TPRD WITH (NOLOCK)
    ),
   
    FLAN AS (
        SELECT IDMOV, IDLAN, NUMERODOCUMENTO, DATAVENCIMENTO, DATABAIXA, DESCSTATUSLCTO, CODDEPARTAMENTO, CODCXA, VALORORIGINAL, VALOROP6, VALORBAIXADO, CODCFO, Descricao_Tipo_Pagamento, HISTORICO, DESCSTATUSCNAB
        FROM CorporeRM.FLAN WITH (NOLOCK)
    ),
   
    FLANBAIXA AS (
        SELECT IDLAN, IDXCX, CODEVENTOBAIXA
        FROM CorporeRM.FLANBAIXA WITH (NOLOCK)
    ),
   
    FCFO AS (
        SELECT CODCFO, CGCCFO, NOMEFANTASIA
        FROM CorporeRM.FCFO WITH (NOLOCK)
    ),
   
    FLANCOMPL AS (
        SELECT IDLAN, CC001, NRESUMO, CODAUTORIZACAOVENDA  
        FROM CorporeRM.FLANCOMPL WITH (NOLOCK)
    ),
   
    FXCX AS (
        SELECT IDXCX, DATACOMPENSACAO, VALOR, CODCXA
        FROM CorporeRM.FXCX
    ),
   
    TOTAL AS (
        SELECT DISTINCT
            E.NUMERODOCUMENTO,
            CONVERT(VARCHAR(10), A.DATAEMISSAO, 103) AS 'DATA EMISSAO',
            CONVERT(VARCHAR(10), E.DATAVENCIMENTO, 103) AS 'DATA VENCIMENTO',
            CONVERT(VARCHAR(10), E.DATABAIXA, 103) AS 'DATA BAIXA',
            E.DESCSTATUSLCTO AS 'STATUS LANCAMENTO',
            E.CODDEPARTAMENTO,
            E.CODCXA,
            E.VALORORIGINAL AS 'VALOR ORIGINAL',
            E.VALOROP6 AS 'ABATIMENTO',
            E.VALORBAIXADO AS 'VALOR BAIXADO',
            H.CGCCFO AS 'CNPJ_CLIENTE',
            H.NOMEFANTASIA AS 'NOME FANTASIA CLIENTE',
            G.NOMEFANTASIA,
            E.Descricao_Tipo_Pagamento AS 'TIPO PAGAMENTO',
            E.HISTORICO,
            F.CODEVENTOBAIXA,
            C.DESCMOV,
            E.DESCSTATUSCNAB AS 'STATUS CNAB',
            I.CC001 AS 'HISTÓRICO DE COBRANÇA',
            J.VALOR AS 'VALOR DO EXTRATO',
            J.CODCXA AS 'CONTA CAIXA',
            J.IDXCX AS 'REF. EXTRATO DE CAIXA'
        FROM TMOV A
        INNER JOIN DESCR_MOV C ON A.CODTMV = C.CODTMV
        LEFT JOIN FLAN E ON A.IDMOV = E.IDMOV
        LEFT JOIN FLANBAIXA F ON E.IDLAN = F.IDLAN
        LEFT JOIN FCFO G ON G.CODCFO = E.CODCFO
        LEFT JOIN FCFO H ON H.CODCFO = A.CODCFO
        LEFT JOIN FLANCOMPL I ON E.IDLAN = I.IDLAN
        LEFT JOIN FXCX J ON F.IDXCX = J.IDXCX
        WHERE E.DESCSTATUSLCTO LIKE 'Em Aberto' AND G.NOMEFANTASIA NOT LIKE '%GETNET%'
    )
   
    , PGTO AS (
        SELECT
            [TIPO PAGAMENTO] AS 'TIPO PAGAMENTO',
            COUNT(*) AS 'QUANTIDADE',
            SUM([VALOR ORIGINAL]) AS 'VALOR ORIGINAL TOTAL'
        FROM TOTAL
        GROUP BY [TIPO PAGAMENTO]
    )
   
    SELECT * FROM PGTO
    ORDER BY QUANTIDADE DESC
    """,
"dpto_query": """
DECLARE @DATAINICIO DATE = '01/01/24';
DECLARE @DATAFIM DATE = GETDATE();

WITH TMOV AS (
    SELECT IDMOV, DATAEMISSAO, CODTMV, CODCFO
    FROM CorporeRM.TMOV WITH (NOLOCK)
    WHERE [DATAEMISSAO] BETWEEN @DATAINICIO AND @DATAFIM
      AND CODTMV IN ('2.1.07','2.1.13','2.1.14','2.2.14')
),
ITMMOV AS (
    SELECT IDMOV, IDPRD
    FROM CorporeRM.TITMMOV WITH (NOLOCK)
),
DESCR_MOV AS (
    SELECT CODTMV, DESCMOV
    FROM [FINANCA].[dbo].[descricao_CODTMV] WITH (NOLOCK)
),
TPRD AS (
    SELECT IDPRD, NOMEFANTASIA
    FROM CorporeRM.TPRD WITH (NOLOCK)
),
FLAN AS (
    SELECT IDMOV, IDLAN, NUMERODOCUMENTO, DATAVENCIMENTO, DATABAIXA, DESCSTATUSLCTO, CODDEPARTAMENTO, CODCXA, VALORORIGINAL, VALOROP6, VALORBAIXADO, CODCFO, Descricao_Tipo_Pagamento, HISTORICO, DESCSTATUSCNAB
    FROM CorporeRM.FLAN WITH (NOLOCK)
),
FLANBAIXA AS (
    SELECT IDLAN, IDXCX, CODEVENTOBAIXA
    FROM CorporeRM.FLANBAIXA WITH (NOLOCK)
),
FCFO AS (
    SELECT CODCFO, CGCCFO, NOMEFANTASIA
    FROM CorporeRM.FCFO WITH (NOLOCK)
),
FLANCOMPL AS (
    SELECT IDLAN, CC001, NRESUMO, CODAUTORIZACAOVENDA
    FROM CorporeRM.FLANCOMPL WITH (NOLOCK)
),
FXCX AS (
    SELECT IDXCX, DATACOMPENSACAO, VALOR, CODCXA
    FROM CorporeRM.FXCX WITH (NOLOCK)
),
TOTAL AS (
    SELECT DISTINCT
        E.NUMERODOCUMENTO,
        CONVERT(VARCHAR(10), A.DATAEMISSAO, 103) AS 'DATA EMISSAO',
        CONVERT(VARCHAR(10), E.DATAVENCIMENTO, 103) AS 'DATA VENCIMENTO',
        CONVERT(VARCHAR(10), E.DATABAIXA, 103) AS 'DATA BAIXA',
        E.DESCSTATUSLCTO AS 'STATUS LANCAMENTO',
        E.CODDEPARTAMENTO,
        E.CODCXA,
        E.VALORORIGINAL AS 'VALOR ORIGINAL',
        E.VALOROP6 AS 'ABATIMENTO',
        E.VALORBAIXADO AS 'VALOR BAIXADO',
        H.CGCCFO AS 'CNPJ_CLIENTE',
        H.NOMEFANTASIA AS 'NOME FANTASIA CLIENTE',
        G.NOMEFANTASIA,
        E.Descricao_Tipo_Pagamento AS 'TIPO PAGAMENTO',
        E.HISTORICO,
        F.CODEVENTOBAIXA,
        C.DESCMOV,
        E.DESCSTATUSCNAB AS 'STATUS CNAB',
        I.CC001 AS 'HISTÓRICO DE COBRANÇA',
        J.VALOR AS 'VALOR DO EXTRATO',
        J.CODCXA AS 'CONTA CAIXA',
        J.IDXCX AS 'REF. EXTRATO DE CAIXA'
    FROM TMOV A
    INNER JOIN DESCR_MOV C ON A.CODTMV = C.CODTMV
    LEFT JOIN FLAN E ON A.IDMOV = E.IDMOV
    LEFT JOIN FLANBAIXA F ON E.IDLAN = F.IDLAN
    LEFT JOIN FCFO G ON G.CODCFO = E.CODCFO
    LEFT JOIN FCFO H ON H.CODCFO = A.CODCFO
    LEFT JOIN FLANCOMPL I ON E.IDLAN = I.IDLAN
    LEFT JOIN FXCX J ON F.IDXCX = J.IDXCX
    WHERE E.DESCSTATUSLCTO LIKE 'Em Aberto'
      AND G.NOMEFANTASIA NOT LIKE '%GETNET%'
),
DPTO AS (
    SELECT
        B.NOME AS 'NOME',
        COUNT(*) AS 'QUANTIDADE',
        SUM([VALOR ORIGINAL]) AS 'VALOR ORIGINAL TOTAL'
    FROM TOTAL A
    INNER JOIN CorporeRM.GDEPTO B
      ON A.CODDEPARTAMENTO COLLATE Latin1_General_CI_AS = B.CODDEPARTAMENTO
    WHERE B.CODFILIAL = '1'
    GROUP BY B.NOME
)
SELECT * FROM DPTO
ORDER BY [VALOR ORIGINAL TOTAL] DESC;
""",
"ano_query": """
    DECLARE @DATAINICIO DATE = '01/01/24';
    DECLARE @DATAFIM DATE = GETDATE();
    
    WITH TMOV AS (
        SELECT IDMOV, DATAEMISSAO, CODTMV, CODCFO
        FROM CorporeRM.TMOV WITH (NOLOCK)
        WHERE [DATAEMISSAO] BETWEEN @DATAINICIO AND @DATAFIM
        AND CODTMV IN ('2.1.07','2.1.13','2.1.14','2.2.14')
    ),
    
    ITMMOV AS (
        SELECT IDMOV, IDPRD
        FROM CorporeRM.TITMMOV WITH (NOLOCK)
    ),
    
    DESCR_MOV AS (
        SELECT CODTMV, DESCMOV
        FROM [FINANCA].[dbo].[descricao_CODTMV] WITH (NOLOCK)
    ),
    
    TPRD AS (
        SELECT IDPRD, NOMEFANTASIA
        FROM CorporeRM.TPRD WITH (NOLOCK)
    ),
    
    FLAN AS (
        SELECT IDMOV, IDLAN, NUMERODOCUMENTO, DATAVENCIMENTO, DATABAIXA, DESCSTATUSLCTO, CODDEPARTAMENTO, CODCXA, VALORORIGINAL, VALOROP6, VALORBAIXADO, CODCFO, Descricao_Tipo_Pagamento, HISTORICO, DESCSTATUSCNAB
        FROM CorporeRM.FLAN WITH (NOLOCK)
    ),
    
    FLANBAIXA AS (
        SELECT IDLAN, IDXCX, CODEVENTOBAIXA
        FROM CorporeRM.FLANBAIXA WITH (NOLOCK)
    ),
    
    FCFO AS (
        SELECT CODCFO, CGCCFO, NOMEFANTASIA
        FROM CorporeRM.FCFO WITH (NOLOCK)
    ),
    
    FLANCOMPL AS (
        SELECT IDLAN, CC001, NRESUMO, CODAUTORIZACAOVENDA  
        FROM CorporeRM.FLANCOMPL WITH (NOLOCK)
    ),
    
    FXCX AS (
        SELECT IDXCX, DATACOMPENSACAO, VALOR, CODCXA
        FROM CorporeRM.FXCX
    ),
    
    TOTAL AS (
        SELECT DISTINCT
            E.NUMERODOCUMENTO,
            CONVERT(VARCHAR(10), A.DATAEMISSAO, 103) AS 'DATA EMISSAO',
            CONVERT(VARCHAR(10), E.DATAVENCIMENTO, 103) AS 'DATA VENCIMENTO',
            CONVERT(VARCHAR(10), E.DATABAIXA, 103) AS 'DATA BAIXA',
            E.DESCSTATUSLCTO AS 'STATUS LANCAMENTO',
            E.CODDEPARTAMENTO,
            E.CODCXA,
            E.VALORORIGINAL AS 'VALOR ORIGINAL',
            E.VALOROP6 AS 'ABATIMENTO',
            E.VALORBAIXADO AS 'VALOR BAIXADO',
            H.CGCCFO AS 'CNPJ_CLIENTE',
            H.NOMEFANTASIA AS 'NOME FANTASIA CLIENTE',
            G.NOMEFANTASIA,
            E.Descricao_Tipo_Pagamento AS 'TIPO PAGAMENTO',
            E.HISTORICO,
            F.CODEVENTOBAIXA,
            C.DESCMOV,
            E.DESCSTATUSCNAB AS 'STATUS CNAB',
            I.CC001 AS 'HISTÓRICO DE COBRANÇA',
            J.VALOR AS 'VALOR DO EXTRATO',
            J.CODCXA AS 'CONTA CAIXA',
            J.IDXCX AS 'REF. EXTRATO DE CAIXA'
        FROM TMOV A
        INNER JOIN DESCR_MOV C ON A.CODTMV = C.CODTMV
        LEFT JOIN FLAN E ON A.IDMOV = E.IDMOV
        LEFT JOIN FLANBAIXA F ON E.IDLAN = F.IDLAN
        LEFT JOIN FCFO G ON G.CODCFO = E.CODCFO
        LEFT JOIN FCFO H ON H.CODCFO = A.CODCFO
        LEFT JOIN FLANCOMPL I ON E.IDLAN = I.IDLAN
        LEFT JOIN FXCX J ON F.IDXCX = J.IDXCX
        WHERE E.DESCSTATUSLCTO LIKE 'Em Aberto' AND G.NOMEFANTASIA NOT LIKE '%GETNET%'
    )
 
 
, ANO AS (SELECT
    FORMAT(CONVERT(DATE, [DATA VENCIMENTO], 103), 'yyyy-MM') AS 'MÊS E ANO',
    COUNT(*) AS 'QUANTIDADE',
    SUM([VALOR ORIGINAL]) AS 'VALOR ORIGINAL TOTAL'
FROM TOTAL
GROUP BY FORMAT(CONVERT(DATE, [DATA VENCIMENTO], 103), 'yyyy-MM')
)
 
SELECT * FROM ANO
ORDER BY [MÊS E ANO] DESC""",
"total_query": """
    DECLARE @DATAINICIO DATE = '01/01/24';
    DECLARE @DATAFIM DATE = GETDATE();
    
    WITH TMOV AS (
        SELECT IDMOV, DATAEMISSAO, CODTMV, CODCFO
        FROM CorporeRM.TMOV WITH (NOLOCK)
        WHERE [DATAEMISSAO] BETWEEN @DATAINICIO AND @DATAFIM
        AND CODTMV IN ('2.1.07','2.1.13','2.1.14','2.2.14')
    ),
    
    ITMMOV AS (
        SELECT IDMOV, IDPRD
        FROM CorporeRM.TITMMOV WITH (NOLOCK)
    ),
    
    DESCR_MOV AS (
        SELECT CODTMV, DESCMOV
        FROM [FINANCA].[dbo].[descricao_CODTMV] WITH (NOLOCK)
    ),
    
    TPRD AS (
        SELECT IDPRD, NOMEFANTASIA
        FROM CorporeRM.TPRD WITH (NOLOCK)
    ),
    
    FLAN AS (
        SELECT IDMOV, IDLAN, NUMERODOCUMENTO, DATAVENCIMENTO, DATABAIXA, DESCSTATUSLCTO, CODDEPARTAMENTO, CODCXA, VALORORIGINAL, VALOROP6, VALORBAIXADO, CODCFO, Descricao_Tipo_Pagamento, HISTORICO, DESCSTATUSCNAB
        FROM CorporeRM.FLAN WITH (NOLOCK)
    ),
    
    FLANBAIXA AS (
        SELECT IDLAN, IDXCX, CODEVENTOBAIXA
        FROM CorporeRM.FLANBAIXA WITH (NOLOCK)
    ),
    
    FCFO AS (
        SELECT CODCFO, CGCCFO, NOMEFANTASIA
        FROM CorporeRM.FCFO WITH (NOLOCK)
    ),
    
    FLANCOMPL AS (
        SELECT IDLAN, CC001, NRESUMO, CODAUTORIZACAOVENDA  
        FROM CorporeRM.FLANCOMPL WITH (NOLOCK)
    ),
    
    FXCX AS (
        SELECT IDXCX, DATACOMPENSACAO, VALOR, CODCXA
        FROM CorporeRM.FXCX
    ),
    
    TOTAL AS (
        SELECT DISTINCT
            E.NUMERODOCUMENTO,
            CONVERT(VARCHAR(10), A.DATAEMISSAO, 103) AS 'DATA EMISSAO',
            CONVERT(VARCHAR(10), E.DATAVENCIMENTO, 103) AS 'DATA VENCIMENTO',
            CONVERT(VARCHAR(10), E.DATABAIXA, 103) AS 'DATA BAIXA',
            E.DESCSTATUSLCTO AS 'STATUS LANCAMENTO',
            E.CODDEPARTAMENTO,
            E.CODCXA,
            E.VALORORIGINAL AS 'VALOR ORIGINAL',
            E.VALOROP6 AS 'ABATIMENTO',
            E.VALORBAIXADO AS 'VALOR BAIXADO',
            H.CGCCFO AS 'CNPJ_CLIENTE',
            H.NOMEFANTASIA AS 'NOME FANTASIA CLIENTE',
            G.NOMEFANTASIA,
            E.Descricao_Tipo_Pagamento AS 'TIPO PAGAMENTO',
            E.HISTORICO,
            F.CODEVENTOBAIXA,
            C.DESCMOV,
            E.DESCSTATUSCNAB AS 'STATUS CNAB',
            I.CC001 AS 'HISTÓRICO DE COBRANÇA',
            J.VALOR AS 'VALOR DO EXTRATO',
            J.CODCXA AS 'CONTA CAIXA',
            J.IDXCX AS 'REF. EXTRATO DE CAIXA'
        FROM TMOV A
        INNER JOIN DESCR_MOV C ON A.CODTMV = C.CODTMV
        LEFT JOIN FLAN E ON A.IDMOV = E.IDMOV
        LEFT JOIN FLANBAIXA F ON E.IDLAN = F.IDLAN
        LEFT JOIN FCFO G ON G.CODCFO = E.CODCFO
        LEFT JOIN FCFO H ON H.CODCFO = A.CODCFO
        LEFT JOIN FLANCOMPL I ON E.IDLAN = I.IDLAN
        LEFT JOIN FXCX J ON F.IDXCX = J.IDXCX
        WHERE E.DESCSTATUSLCTO LIKE 'Em Aberto' AND G.NOMEFANTASIA NOT LIKE '%GETNET%'
    )
 
 
SELECT * FROM TOTAL
"""
}